# Generated by Django 2.1.5 on 2019-01-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthday',
            new_name='birth',
        ),
    ]
